/* eslint-disable max-lines */
import { getAvatarUrl } from '../utils/avatarUtils';
import type { Evaluation, EvaluationTemplate, Headquarter, LeaderHistory, Team } from './types';

export const initialLeaderHistory: LeaderHistory[] = [
    {
        id: 'hist_1',
        headquarterId: 'hq-cloud',
        leaderName: '장주휘',
        action: 'appointed', // 최초 임명
        timestamp: '2022-01-01',
    },
];

const DEFAULT_HEADQUARTER_LEADER: Headquarter['leader'] = {
    name: '장주휘',
    role: '본부장',
    avatar: getAvatarUrl('장주휘'),
    email: 'juwhijang@forcs.com',
} as const;

export const initialHeadquarters: Headquarter[] = [
    {
        id: 'hq-cloud',
        name: '클라우드사업본부',
        leader: { ...DEFAULT_HEADQUARTER_LEADER },
        description: '클라우드 기반 서비스 전략과 영업을 총괄합니다.',
    },
];

export const currentUser = {
    name: '조병철',
    role: '영업관리',
    avatar: getAvatarUrl('조병철'),
    email: 'rayben@forcs.com',
};

export const TEAM_LEADER_TEAM_ID = 'team_sales';
export const TEAM_LEADER_TEAM_NAME = 'Sales팀';

export const HQ_UNASSIGNED_ID = 'hq-unassigned';

export const initialTeamsData: Team[] = [
    {
        id: 'team_sales',
        headquarterId: 'hq-cloud',
        name: 'Sales팀',
        lead: '장주휘',
        parts: [
            {
                id: 'part_sales_manage',
                title: '영업관리파트',
                members: [
                    {
                        id: 'mem_chobyungchul',
                        name: '조병철',
                        role: '영업관리',
                        avatar: getAvatarUrl('조병철'),
                        status: 'active',
                        hireDate: '2022-03-15',
                        email: 'rayben@forcs.com',
                    },
                ],
            },
            {
                id: 'part_sales',
                title: 'Sales파트',
                members: [
                    {
                        id: 'mem_choimin',
                        name: '최민',
                        role: 'Sales',
                        avatar: getAvatarUrl('최민'),
                        status: 'active',
                        hireDate: '2021-08-01',
                        email: 'minchoi@forcs.com',
                    },
                    {
                        id: 'mem_kimdamin',
                        name: '김다민',
                        role: 'Sales',
                        avatar: getAvatarUrl('김다민'),
                        status: 'active',
                        hireDate: '2024-06-01',
                        email: 'manypeople@forcs.com',
                    },
                    {
                        id: 'mem_parkjinhee',
                        name: '박진희',
                        role: 'Sales',
                        avatar: getAvatarUrl('박진희'),
                        status: 'on_leave',
                        hireDate: '2022-11-20',
                        email: 'jinhee@forcs.com',
                    },
                    {
                        id: 'mem_parkjiwoo',
                        name: '박지우',
                        role: 'Sales',
                        avatar: getAvatarUrl('박지우'),
                        status: 'resigned',
                        hireDate: '2022-05-10',
                        email: 'jiwoo@forcs.com',
                    },
                ],
            },
        ],
    },
    {
        id: 'team_cx',
        headquarterId: 'hq-cloud',
        name: 'CX팀',
        lead: '정현옥',
        parts: [
            {
                id: 'part_tech_support',
                title: '기술지원파트',
                members: [
                    {
                        id: 'mem_kimsohyun',
                        name: '김소현',
                        role: '기술지원',
                        avatar: getAvatarUrl('김소현'),
                        status: 'active',
                        hireDate: '2023-01-10',
                        email: 'kimsohyeon@forcs.com',
                    },
                    {
                        id: 'mem_leejaehyuk',
                        name: '이재혁',
                        role: '기술지원',
                        avatar: getAvatarUrl('이재혁'),
                        status: 'active',
                        hireDate: '2023-05-22',
                        email: 'encrabell@forcs.com',
                    },
                    {
                        id: 'mem_leeseojun',
                        name: '이서준',
                        role: '기술지원',
                        avatar: getAvatarUrl('이서준'),
                        status: 'on_leave',
                        hireDate: '2023-08-01',
                        email: 'seojun@forcs.com',
                    },
                ],
            },
            {
                id: 'part_tech_writing',
                title: '테크니컬라이팅파트',
                members: [
                    {
                        id: 'mem_choichulhwan',
                        name: '최철환',
                        role: 'Technical Writing',
                        avatar: getAvatarUrl('최철환'),
                        status: 'active',
                        hireDate: '2020-02-18',
                        email: 'davidchoi@forcs.com',
                    },
                ],
            },
            {
                id: 'part_tech_marketing',
                title: '테크니컬마케팅파트',
                members: [
                    {
                        id: 'mem_jangnayoung',
                        name: '장나영',
                        role: 'Technical Marketing',
                        avatar: getAvatarUrl('장나영'),
                        status: 'active',
                        hireDate: '2021-09-01',
                        email: 'nayoungj@forcs.com',
                    },
                ],
            },
            {
                id: 'part_biz_ops',
                title: '사업운영파트',
                members: [
                    {
                        id: 'mem_junghyunok',
                        name: '정현옥',
                        role: 'CX팀 팀장',
                        avatar: getAvatarUrl('정현옥'),
                        status: 'active',
                        hireDate: '2019-07-15',
                        email: 'hyunok@forcs.com',
                    },
                    {
                        id: 'mem_leedahee',
                        name: '이다희',
                        role: '사업운영',
                        avatar: getAvatarUrl('이다희'),
                        status: 'active',
                        hireDate: '2022-10-03',
                        email: 'dhlee@forcs.com',
                    },
                    {
                        id: 'mem_kimdabin',
                        name: '김다빈',
                        role: '사업운영',
                        avatar: getAvatarUrl('김다빈'),
                        status: 'active',
                        hireDate: '2023-09-11',
                        email: 'oed1223@forcs.com',
                    },
                ],
            },
            {
                id: 'part_customer_service',
                title: '고객서비스파트',
                members: [
                    {
                        id: 'mem_parksarang',
                        name: '박사랑',
                        role: '고객서비스',
                        avatar: getAvatarUrl('박사랑'),
                        status: 'active',
                        hireDate: '2022-04-04',
                        email: 'sarang@forcs.com',
                    },
                    {
                        id: 'mem_heoahyoung',
                        name: '허아영',
                        role: '고객서비스',
                        avatar: getAvatarUrl('허아영'),
                        status: 'active',
                        hireDate: '2023-02-20',
                        email: 'heoayoung@forcs.com',
                    },
                    {
                        id: 'mem_kimtaeeun',
                        name: '김태은',
                        role: '고객서비스',
                        avatar: getAvatarUrl('김태은'),
                        status: 'active',
                        hireDate: '2023-11-06',
                        email: 'kte0701@forcs.com',
                    },
                    {
                        id: 'mem_choitaehyun',
                        name: '최현',
                        role: 'CX팀 인턴',
                        avatar: getAvatarUrl('최현'),
                        status: 'active',
                        employmentType: 'intern',
                        hireDate: '2024-08-01',
                        email: 'choinhwan@forcs.com',
                    },
                    {
                        id: 'mem_leejunsu',
                        name: '이준수',
                        role: 'CX팀 인턴',
                        avatar: getAvatarUrl('이준수'),
                        status: 'active',
                        employmentType: 'intern',
                        hireDate: '2024-08-01',
                        email: 'js@forcs.com',
                    },
                    {
                        id: 'mem_limjaeeon',
                        name: '임재언',
                        role: 'CX팀 인턴',
                        avatar: getAvatarUrl('임재언'),
                        status: 'active',
                        employmentType: 'intern',
                        hireDate: '2024-08-01',
                        email: 'lim063033@gmail.com',
                    },
                    {
                        id: 'mem_kimseoeun',
                        name: '김서은',
                        role: 'CX팀 인턴',
                        avatar: getAvatarUrl('김서은'),
                        status: 'active',
                        employmentType: 'intern',
                        hireDate: '2024-08-01',
                        email: 'seoeun@forcs.com',
                    },
                    {
                        id: 'mem_leenaeun',
                        name: '이나은',
                        role: 'CX팀 인턴',
                        avatar: getAvatarUrl('이나은'),
                        status: 'active',
                        employmentType: 'intern',
                        hireDate: '2024-08-01',
                        email: 'naeunlee@forcs.com',
                    },
                ],
            },
        ],
    },
];

export const initialEvaluationsData: Evaluation[] = [
    {
        id: 1,
        name: '2024년 상반기 성과 평가',
        type: '본인평가',
        period: '상반기',
        status: '완료',
        subject: '장주휘', // Changed from Division to Person for clarity in this demo context or kept as is? The original was '클라우드사업본부'. Let's keep it but assign HQ ID? Actually, let's map it to the Leader for better continuity demo.
        subjectId: 'leader_jang',
        subjectSnapshot: {
            name: '장주휘',
            role: '본부장',
            teamId: 'hq-cloud', // Using HQ ID as teamID placeholder for HQ lead
            teamName: '클라우드사업본부',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-04-01',
        endDate: '2024-04-15',
        progress: 100,
        score: 95,
    },
    {
        id: 2,
        name: '2024년 하반기 성과 평가',
        type: '본인평가',
        period: '하반기',
        status: '진행중',
        subject: '장주휘',
        subjectId: 'leader_jang',
        subjectSnapshot: {
            name: '장주휘',
            role: '본부장',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-10-01',
        endDate: '2024-10-15',
        progress: 10,
        score: null,
    },
    {
        id: 3,
        name: '신규 입사자 수습 평가',
        type: '본인평가',
        period: '수시',
        status: '진행중',
        subject: '김다민',
        subjectId: 'mem_kimdamin',
        subjectSnapshot: {
            name: '김다민',
            role: 'Sales',
            teamId: 'team_sales',
            teamName: 'Sales팀',
            partId: 'part_sales',
            partName: 'Sales파트',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-06-20',
        endDate: '2024-07-05',
        progress: 50,
        score: null,
    },
    {
        id: 4,
        name: '리더십 역량 진단',
        type: '다면평가',
        period: '연간',
        status: '완료',
        subject: '팀장 그룹',
        subjectId: 'group_leads', // Group ID
        subjectSnapshot: {
            name: '팀장 그룹',
            role: 'Group',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
        },
        startDate: '2024-05-10',
        endDate: '2024-05-25',
        progress: 100,
        score: 88,
    },
    {
        id: 5,
        name: '2024년 동료 피드백',
        type: '다면평가',
        period: '연간',
        status: '완료',
        subject: 'CX팀',
        subjectId: 'team_cx', // Team ID
        subjectSnapshot: {
            name: 'CX팀',
            role: 'Team',
            teamId: 'team_cx',
            teamName: 'CX팀',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-06-01',
        endDate: '2024-06-10',
        progress: 100,
        score: 92,
    },
    {
        id: 6,
        name: '2025년 상반기 성과 평가',
        type: '본인평가',
        period: '상반기',
        status: '예정',
        subject: '클라우드사업본부',
        subjectId: 'hq-cloud',
        subjectSnapshot: {
            name: '클라우드사업본부',
            role: 'Headquarter',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
        },
        startDate: '2025-04-01',
        endDate: '2025-04-15',
        progress: 0,
        score: null,
    },
    {
        id: 7,
        name: '2024년 Sales팀장 성과 평가',
        type: '본인평가',
        period: '연간',
        status: '완료',
        subject: '장주휘',
        subjectId: 'leader_jang',
        subjectSnapshot: {
            name: '장주휘',
            role: '본부장', // Originally Team Lead? But name is same as HQ lead. Let's assume he is acting team lead too or it's a diff person? In mockData teams, lead is '장주휘'.
            teamId: 'team_sales',
            teamName: 'Sales팀',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-11-01',
        endDate: '2024-11-15',
        progress: 100,
        score: 91,
    },
    {
        id: 8,
        name: '2024년 CX팀장 성과 평가',
        type: '본인평가',
        period: '연간',
        status: '진행중',
        subject: '정현옥',
        subjectId: 'mem_junghyunok',
        subjectSnapshot: {
            name: '정현옥',
            role: 'CX팀 팀장',
            teamId: 'team_cx',
            teamName: 'CX팀',
            partId: 'part_biz_ops',
            partName: '사업운영파트',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-11-01',
        endDate: '2024-11-30',
        progress: 60,
        score: null,
    },
    {
        id: 9,
        name: '2024년 Sales팀 동료 피드백',
        type: '다면평가',
        period: '연간',
        status: '완료',
        subject: 'Sales팀',
        subjectId: 'team_sales',
        subjectSnapshot: {
            name: 'Sales팀',
            role: 'Team',
            teamId: 'team_sales',
            teamName: 'Sales팀',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-06-01',
        endDate: '2024-06-10',
        progress: 100,
        score: 89,
    },
];

export const initialLibraryData: EvaluationTemplate[] = [
    {
        id: 1,
        name: '역량 평가 (공통)',
        type: '역량 평가',
        category: '공통',
        tags: ['공통', '역량'],
        version: 1,
        questions: 12,
        lastUpdated: '2024-05-10',
        author: '장주휘',
    },
    {
        id: 2,
        name: '프로젝트 동료 피드백',
        type: '다면 평가',
        category: '개발',
        tags: ['프로젝트', '협업'],
        version: 1,
        questions: 8,
        lastUpdated: '2024-06-15',
        author: '정현옥',
    },
    {
        id: 3,
        name: '신규 입사자 수습 평가',
        type: '수습 평가',
        category: '공통',
        tags: ['온보딩'],
        version: 1,
        questions: 15,
        lastUpdated: '2024-04-20',
        author: '장주휘',
    },
    {
        id: 4,
        name: '리더십 역량 진단',
        type: '리더십 평가',
        category: '리더십',
        tags: ['리더십'],
        version: 1,
        questions: 20,
        lastUpdated: '2024-03-01',
        author: '시스템',
    },
    {
        id: 5,
        name: 'Sales 직군 역량 평가',
        type: '역량 평가',
        category: '영업',
        tags: ['영업'],
        version: 1,
        questions: 10,
        lastUpdated: '2024-07-01',
        author: '장주휘',
    },
];

export const evaluationResultData = {
    evaluationId: 1,
    subject: {
        name: '장주휘',
        role: '본부장',
        avatar: getAvatarUrl('장주휘'),
    },
    evaluationName: '2024년 상반기 성과 평가',
    period: '2024-04-01 ~ 2024-04-15',
    finalScore: 95,
    finalGrade: 'S',
    summary:
        '전반적으로 모든 역량에서 뛰어난 성과를 보여주셨습니다. 특히 리더십과 문제 해결 능력에서 높은 평가를 받았습니다. 동료들과의 협업 능력 또한 탁월하며, 팀에 긍정적인 영향을 미치고 있습니다.',
    competencies: [
        { name: '리더십', selfScore: 90, peerScore: 98, finalScore: 96 },
        { name: '문제 해결 능력', selfScore: 95, peerScore: 92, finalScore: 93 },
        { name: '커뮤니케이션', selfScore: 85, peerScore: 95, finalScore: 92 },
        { name: '팀워크', selfScore: 92, peerScore: 96, finalScore: 95 },
        { name: '업무 전문성', selfScore: 88, peerScore: 90, finalScore: 89 },
    ],
    strengths: [
        '강력한 리더십으로 팀의 목표 달성을 이끌었습니다.',
        '복잡한 문제에 대한 창의적인 해결책을 제시했습니다.',
        '항상 긍정적인 태도로 동료들에게 동기를 부여합니다.',
    ],
    areasForImprovement: [
        '업무 위임 시 조금 더 명확한 가이드라인을 제공하면 좋겠습니다.',
        '다양한 직무의 동료들과의 소통을 더욱 활성화할 필요가 있습니다.',
    ],
    peerFeedback: [
        {
            from: '동료 1',
            comment:
                '장주휘님은 항상 팀의 방향성을 명확하게 제시해주어 업무에 집중하기 좋습니다. 어려운 문제가 발생했을 때 함께 고민하고 해결해나가는 과정에서 많이 배우고 있습니다.',
        },
        {
            from: '동료 2',
            comment:
                '프로젝트 진행 상황을 투명하게 공유하고, 동료들의 의견을 적극적으로 경청하는 모습이 인상적이었습니다. 덕분에 팀 전체가 시너지를 낼 수 있었습니다.',
        },
        {
            from: '동료 3',
            comment:
                '가끔 업무 지시가 조금 더 구체적이었으면 하는 아쉬움이 있습니다. 하지만 언제나 피드백에 열려있어 소통하는 데 어려움은 없습니다.',
        },
    ],
};
