import { getAvatarUrl } from '../../utils/avatarUtils';
import { initialLibraryData } from './templates';
import type { Evaluation } from '../types';

const monthlyPerformanceTemplate =
    initialLibraryData.find((template) => template.id === 6) || initialLibraryData[0];

export const initialEvaluationsData: Evaluation[] = [
    {
        id: 1,
        name: '2024년 상반기 성과 평가',
        type: '본인평가',
        period: '상반기',
        status: '완료',
        subject: '장주휘',
        subjectId: 'leader_jang',
        subjectSnapshot: {
            name: '장주휘',
            role: '본부장',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-04-01',
        endDate: '2024-04-15',
        progress: 100,
        score: 95,
    },
    {
        id: 2,
        name: '2024년 하반기 성과 평가',
        type: '본인평가',
        period: '하반기',
        status: '진행중',
        subject: '장주휘',
        subjectId: 'leader_jang',
        subjectSnapshot: {
            name: '장주휘',
            role: '본부장',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-10-01',
        endDate: '2024-10-15',
        progress: 10,
        score: null,
    },
    {
        id: 3,
        name: '신규 입사자 수습 평가',
        type: '본인평가',
        period: '수시',
        status: '진행중',
        subject: '김다민',
        subjectId: 'mem_kimdamin',
        subjectSnapshot: {
            name: '김다민',
            role: 'Sales',
            teamId: 'team_sales',
            teamName: 'Sales팀',
            partId: 'part_sales',
            partName: 'Sales파트',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-06-20',
        endDate: '2024-07-05',
        progress: 50,
        score: null,
    },
    {
        id: 4,
        name: '리더십 역량 진단',
        type: '다면평가',
        period: '연간',
        status: '완료',
        subject: '팀장 그룹',
        subjectId: 'group_leads',
        subjectSnapshot: {
            name: '팀장 그룹',
            role: 'Group',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
        },
        startDate: '2024-05-10',
        endDate: '2024-05-25',
        progress: 100,
        score: 88,
    },
    {
        id: 5,
        name: '2024년 동료 피드백',
        type: '다면평가',
        period: '연간',
        status: '완료',
        subject: 'CX팀',
        subjectId: 'team_cx',
        subjectSnapshot: {
            name: 'CX팀',
            role: 'Team',
            teamId: 'team_cx',
            teamName: 'CX팀',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-06-01',
        endDate: '2024-06-10',
        progress: 100,
        score: 92,
    },
    {
        id: 6,
        name: '2025년 상반기 성과 평가',
        type: '본인평가',
        period: '상반기',
        status: '예정',
        subject: '클라우드사업본부',
        subjectId: 'hq-cloud',
        subjectSnapshot: {
            name: '클라우드사업본부',
            role: 'Headquarter',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
        },
        startDate: '2025-04-01',
        endDate: '2025-04-15',
        progress: 0,
        score: null,
    },
    {
        id: 10,
        name: '2025년 7월 월별 성과 평가',
        type: '본인평가',
        period: '월별',
        cycleKey: '2025-07',
        ratingScale: '100점',
        scoringRule: '총점합산',
        templateSnapshot: monthlyPerformanceTemplate,
        status: '완료',
        subject: '클라우드사업본부',
        subjectId: 'hq-cloud',
        subjectSnapshot: {
            name: '클라우드사업본부',
            role: 'Headquarter',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
        },
        startDate: '2025-07-01',
        endDate: '2025-07-31',
        progress: 100,
        score: 86,
    },
    {
        id: 11,
        name: '2025년 8월 월별 성과 평가',
        type: '본인평가',
        period: '월별',
        cycleKey: '2025-08',
        ratingScale: '100점',
        scoringRule: '총점합산',
        templateSnapshot: monthlyPerformanceTemplate,
        status: '완료',
        subject: '클라우드사업본부',
        subjectId: 'hq-cloud',
        subjectSnapshot: {
            name: '클라우드사업본부',
            role: 'Headquarter',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
        },
        startDate: '2025-08-01',
        endDate: '2025-08-31',
        progress: 100,
        score: 88,
    },
    {
        id: 12,
        name: '2025년 9월 월별 성과 평가',
        type: '본인평가',
        period: '월별',
        cycleKey: '2025-09',
        ratingScale: '100점',
        scoringRule: '총점합산',
        templateSnapshot: monthlyPerformanceTemplate,
        status: '완료',
        subject: '클라우드사업본부',
        subjectId: 'hq-cloud',
        subjectSnapshot: {
            name: '클라우드사업본부',
            role: 'Headquarter',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
        },
        startDate: '2025-09-01',
        endDate: '2025-09-30',
        progress: 100,
        score: 84,
    },
    {
        id: 13,
        name: '2025년 10월 월별 성과 평가',
        type: '본인평가',
        period: '월별',
        cycleKey: '2025-10',
        ratingScale: '100점',
        scoringRule: '총점합산',
        templateSnapshot: monthlyPerformanceTemplate,
        status: '완료',
        subject: '클라우드사업본부',
        subjectId: 'hq-cloud',
        subjectSnapshot: {
            name: '클라우드사업본부',
            role: 'Headquarter',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
        },
        startDate: '2025-10-01',
        endDate: '2025-10-31',
        progress: 100,
        score: 90,
    },
    {
        id: 14,
        name: '2025년 11월 월별 성과 평가',
        type: '본인평가',
        period: '월별',
        cycleKey: '2025-11',
        ratingScale: '100점',
        scoringRule: '총점합산',
        templateSnapshot: monthlyPerformanceTemplate,
        status: '완료',
        subject: '클라우드사업본부',
        subjectId: 'hq-cloud',
        subjectSnapshot: {
            name: '클라우드사업본부',
            role: 'Headquarter',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
        },
        startDate: '2025-11-01',
        endDate: '2025-11-30',
        progress: 100,
        score: 87,
    },
    {
        id: 15,
        name: '2025년 12월 월별 성과 평가',
        type: '본인평가',
        period: '월별',
        cycleKey: '2025-12',
        ratingScale: '100점',
        scoringRule: '총점합산',
        templateSnapshot: monthlyPerformanceTemplate,
        status: '완료',
        subject: '클라우드사업본부',
        subjectId: 'hq-cloud',
        subjectSnapshot: {
            name: '클라우드사업본부',
            role: 'Headquarter',
            teamId: 'hq-cloud',
            teamName: '클라우드사업본부',
        },
        startDate: '2025-12-01',
        endDate: '2025-12-31',
        progress: 100,
        score: 89,
    },
    {
        id: 7,
        name: '2024년 Sales팀장 성과 평가',
        type: '본인평가',
        period: '연간',
        status: '완료',
        subject: '장주휘',
        subjectId: 'leader_jang',
        subjectSnapshot: {
            name: '장주휘',
            role: '본부장',
            teamId: 'team_sales',
            teamName: 'Sales팀',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-11-01',
        endDate: '2024-11-15',
        progress: 100,
        score: 91,
    },
    {
        id: 8,
        name: '2024년 CX팀장 성과 평가',
        type: '본인평가',
        period: '연간',
        status: '진행중',
        subject: '정현옥',
        subjectId: 'mem_junghyunok',
        subjectSnapshot: {
            name: '정현옥',
            role: 'CX팀 팀장',
            teamId: 'team_cx',
            teamName: 'CX팀',
            partId: 'part_biz_ops',
            partName: '사업운영파트',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-11-01',
        endDate: '2024-11-30',
        progress: 60,
        score: null,
    },
    {
        id: 9,
        name: '2024년 Sales팀 동료 피드백',
        type: '다면평가',
        period: '연간',
        status: '완료',
        subject: 'Sales팀',
        subjectId: 'team_sales',
        subjectSnapshot: {
            name: 'Sales팀',
            role: 'Team',
            teamId: 'team_sales',
            teamName: 'Sales팀',
            headquarterId: 'hq-cloud',
        },
        startDate: '2024-06-01',
        endDate: '2024-06-10',
        progress: 100,
        score: 89,
    },
];

export const evaluationResultData = {
    evaluationId: 1,
    subject: {
        name: '장주휘',
        role: '본부장',
        avatar: getAvatarUrl('장주휘'),
    },
    evaluationName: '2024년 상반기 성과 평가',
    period: '2024-04-01 ~ 2024-04-15',
    finalScore: 95,
    finalGrade: 'S',
    summary:
        '전반적으로 모든 역량에서 뛰어난 성과를 보여주셨습니다. 특히 리더십과 문제 해결 능력에서 높은 평가를 받았습니다. 동료들과의 협업 능력 또한 탁월하며, 팀에 긍정적인 영향을 미치고 있습니다.',
    competencies: [
        { name: '리더십', selfScore: 90, peerScore: 98, finalScore: 96 },
        { name: '문제 해결 능력', selfScore: 95, peerScore: 92, finalScore: 93 },
        { name: '커뮤니케이션', selfScore: 85, peerScore: 95, finalScore: 92 },
        { name: '팀워크', selfScore: 92, peerScore: 96, finalScore: 95 },
        { name: '업무 전문성', selfScore: 88, peerScore: 90, finalScore: 89 },
    ],
    strengths: [
        '강력한 리더십으로 팀의 목표 달성을 이끌었습니다.',
        '복잡한 문제에 대한 창의적인 해결책을 제시했습니다.',
        '항상 긍정적인 태도로 동료들에게 동기를 부여합니다.',
    ],
    areasForImprovement: [
        '업무 위임 시 조금 더 명확한 가이드라인을 제공하면 좋겠습니다.',
        '다양한 직무의 동료들과의 소통을 더욱 활성화할 필요가 있습니다.',
    ],
    peerFeedback: [
        {
            from: '동료 1',
            comment:
                '장주휘님은 항상 팀의 방향성을 명확하게 제시해주어 업무에 집중하기 좋습니다. 어려운 문제가 발생했을 때 함께 고민하고 해결해나가는 과정에서 많이 배우고 있습니다.',
        },
        {
            from: '동료 2',
            comment:
                '프로젝트 진행 상황을 투명하게 공유하고, 동료들의 의견을 적극적으로 경청하는 모습이 인상적이었습니다. 덕분에 팀 전체가 시너지를 낼 수 있었습니다.',
        },
        {
            from: '동료 3',
            comment:
                '가끔 업무 지시가 조금 더 구체적이었으면 하는 아쉬움이 있습니다. 하지만 언제나 피드백에 열려있어 소통하는 데 어려움은 없습니다.',
        },
    ],
};
