import { getAvatarUrl } from '../../utils/avatarUtils';
import type { Team } from '../types';

export const TEAM_LEADER_TEAM_ID = 'team_sales';
export const TEAM_LEADER_TEAM_NAME = 'Sales팀';

export const initialTeamsData: Team[] = [
    {
        id: 'team_sales',
        headquarterId: 'hq-cloud',
        name: 'Sales팀',
        lead: '장주휘',
        parts: [
            {
                id: 'part_sales_manage',
                title: '영업관리파트',
                members: [
                    {
                        id: 'mem_chobyungchul',
                        name: '조병철',
                        role: '영업관리',
                        avatar: getAvatarUrl('조병철'),
                        status: 'active',
                        hireDate: '2022-03-15',
                        email: 'rayben@forcs.com',
                    },
                ],
            },
            {
                id: 'part_sales',
                title: 'Sales파트',
                members: [
                    {
                        id: 'mem_choimin',
                        name: '최민',
                        role: 'Sales',
                        avatar: getAvatarUrl('최민'),
                        status: 'active',
                        hireDate: '2021-08-01',
                        email: 'minchoi@forcs.com',
                    },
                    {
                        id: 'mem_kimdamin',
                        name: '김다민',
                        role: 'Sales',
                        avatar: getAvatarUrl('김다민'),
                        status: 'active',
                        hireDate: '2024-06-01',
                        email: 'manypeople@forcs.com',
                    },
                    {
                        id: 'mem_parkjinhee',
                        name: '박진희',
                        role: 'Sales',
                        avatar: getAvatarUrl('박진희'),
                        status: 'on_leave',
                        hireDate: '2022-11-20',
                        email: 'jinhee@forcs.com',
                    },
                    {
                        id: 'mem_parkjiwoo',
                        name: '박지우',
                        role: 'Sales',
                        avatar: getAvatarUrl('박지우'),
                        status: 'resigned',
                        hireDate: '2022-05-10',
                        email: 'jiwoo@forcs.com',
                    },
                ],
            },
        ],
    },
    {
        id: 'team_cx',
        headquarterId: 'hq-cloud',
        name: 'CX팀',
        lead: '정현옥',
        parts: [
            {
                id: 'part_tech_support',
                title: '기술지원파트',
                members: [
                    {
                        id: 'mem_kimsohyun',
                        name: '김소현',
                        role: '기술지원',
                        avatar: getAvatarUrl('김소현'),
                        status: 'active',
                        hireDate: '2023-01-10',
                        email: 'kimsohyeon@forcs.com',
                    },
                    {
                        id: 'mem_leejaehyuk',
                        name: '이재혁',
                        role: '기술지원',
                        avatar: getAvatarUrl('이재혁'),
                        status: 'active',
                        hireDate: '2023-05-22',
                        email: 'encrabell@forcs.com',
                    },
                    {
                        id: 'mem_leeseojun',
                        name: '이서준',
                        role: '기술지원',
                        avatar: getAvatarUrl('이서준'),
                        status: 'on_leave',
                        hireDate: '2023-08-01',
                        email: 'seojun@forcs.com',
                    },
                ],
            },
            {
                id: 'part_tech_writing',
                title: '테크니컬라이팅파트',
                members: [
                    {
                        id: 'mem_choichulhwan',
                        name: '최철환',
                        role: 'Technical Writing',
                        avatar: getAvatarUrl('최철환'),
                        status: 'active',
                        hireDate: '2020-02-18',
                        email: 'davidchoi@forcs.com',
                    },
                ],
            },
            {
                id: 'part_tech_marketing',
                title: '테크니컬마케팅파트',
                members: [
                    {
                        id: 'mem_jangnayoung',
                        name: '장나영',
                        role: 'Technical Marketing',
                        avatar: getAvatarUrl('장나영'),
                        status: 'active',
                        hireDate: '2021-09-01',
                        email: 'nayoungj@forcs.com',
                    },
                ],
            },
            {
                id: 'part_biz_ops',
                title: '사업운영파트',
                members: [
                    {
                        id: 'mem_junghyunok',
                        name: '정현옥',
                        role: 'CX팀 팀장',
                        avatar: getAvatarUrl('정현옥'),
                        status: 'active',
                        hireDate: '2019-07-15',
                        email: 'hyunok@forcs.com',
                    },
                    {
                        id: 'mem_leedahee',
                        name: '이다희',
                        role: '사업운영',
                        avatar: getAvatarUrl('이다희'),
                        status: 'active',
                        hireDate: '2022-10-03',
                        email: 'dhlee@forcs.com',
                    },
                    {
                        id: 'mem_kimdabin',
                        name: '김다빈',
                        role: '사업운영',
                        avatar: getAvatarUrl('김다빈'),
                        status: 'active',
                        hireDate: '2023-09-11',
                        email: 'oed1223@forcs.com',
                    },
                ],
            },
            {
                id: 'part_customer_service',
                title: '고객서비스파트',
                members: [
                    {
                        id: 'mem_parksarang',
                        name: '박사랑',
                        role: '고객서비스',
                        avatar: getAvatarUrl('박사랑'),
                        status: 'active',
                        hireDate: '2022-04-04',
                        email: 'sarang@forcs.com',
                    },
                    {
                        id: 'mem_heoahyoung',
                        name: '허아영',
                        role: '고객서비스',
                        avatar: getAvatarUrl('허아영'),
                        status: 'active',
                        hireDate: '2023-02-20',
                        email: 'heoayoung@forcs.com',
                    },
                    {
                        id: 'mem_kimtaeeun',
                        name: '김태은',
                        role: '고객서비스',
                        avatar: getAvatarUrl('김태은'),
                        status: 'active',
                        hireDate: '2023-11-06',
                        email: 'kte0701@forcs.com',
                    },
                    {
                        id: 'mem_choitaehyun',
                        name: '최현',
                        role: 'CX팀 인턴',
                        avatar: getAvatarUrl('최현'),
                        status: 'active',
                        employmentType: 'intern',
                        hireDate: '2024-08-01',
                        email: 'choinhwan@forcs.com',
                    },
                    {
                        id: 'mem_leejunsu',
                        name: '이준수',
                        role: 'CX팀 인턴',
                        avatar: getAvatarUrl('이준수'),
                        status: 'active',
                        employmentType: 'intern',
                        hireDate: '2024-08-01',
                        email: 'js@forcs.com',
                    },
                    {
                        id: 'mem_limjaeeon',
                        name: '임재언',
                        role: 'CX팀 인턴',
                        avatar: getAvatarUrl('임재언'),
                        status: 'active',
                        employmentType: 'intern',
                        hireDate: '2024-08-01',
                        email: 'lim063033@gmail.com',
                    },
                    {
                        id: 'mem_kimseoeun',
                        name: '김서은',
                        role: 'CX팀 인턴',
                        avatar: getAvatarUrl('김서은'),
                        status: 'active',
                        employmentType: 'intern',
                        hireDate: '2024-08-01',
                        email: 'seoeun@forcs.com',
                    },
                    {
                        id: 'mem_leenaeun',
                        name: '이나은',
                        role: 'CX팀 인턴',
                        avatar: getAvatarUrl('이나은'),
                        status: 'active',
                        employmentType: 'intern',
                        hireDate: '2024-08-01',
                        email: 'naeunlee@forcs.com',
                    },
                ],
            },
        ],
    },
];
