import type { EvaluationItem, EvaluationTemplate } from '../types';

const buildScoring = (scores: number[], descriptions: string[]) =>
    scores.map((score, index) => ({
        grade: ['S', 'A', 'B', 'C', 'D'][index] || `${score}점`,
        description: descriptions[index] || '',
        score,
    }));

const scoring10 = buildScoring([10, 8, 6, 4, 2], [
    '기대를 월등히 초과',
    '기대를 상회',
    '기대에 부합',
    '기대에 미흡',
    '개선 필요',
]);
const scoring20 = buildScoring([20, 16, 12, 8, 4], [
    '목표 120% 이상 달성',
    '목표 110% 이상 달성',
    '목표 100% 이상 달성',
    '목표 90% 이상 달성',
    '목표 90% 미만',
]);
const scoring5 = buildScoring([5, 4, 3, 2, 1], [
    '탁월',
    '우수',
    '양호',
    '미흡',
    '부족',
]);

const cloneScoring = (scoring: EvaluationItem['scoring']) => scoring.map((entry) => ({ ...entry }));

export const initialLibraryData: EvaluationTemplate[] = [
    {
        id: 1,
        name: '역량 평가 (공통)',
        type: '역량 평가',
        category: '공통',
        tags: ['공통', '역량'],
        version: 1,
        questions: 12,
        lastUpdated: '2024-05-10',
        author: '장주휘',
    },
    {
        id: 6,
        name: '하반기 월별 성과 평가',
        type: '성과 평가',
        category: '공통',
        tags: ['하반기', '월별', '성과'],
        version: 1,
        questions: 10,
        description:
            '정성 70점(10점 x 7항목) + 정량 30점(20점 x 1항목, 5점 x 2항목)으로 월별 100점 만점 구성.',
        lastUpdated: '2024-08-01',
        author: '시스템',
        items: [
            {
                id: 601,
                type: '정성',
                title: '목표 달성을 위한 실행력',
                weight: 0,
                details: { description: '월별 목표를 구체화하고 일정에 맞게 실행하는 능력' },
                scoringType: '5grade',
                scoring: cloneScoring(scoring10),
            },
            {
                id: 602,
                type: '정성',
                title: '업무 품질 및 완성도',
                weight: 0,
                details: { description: '산출물의 정확성/완성도와 품질 기준 준수' },
                scoringType: '5grade',
                scoring: cloneScoring(scoring10),
            },
            {
                id: 603,
                type: '정성',
                title: '문제 해결 및 개선 노력',
                weight: 0,
                details: { description: '이슈를 분석하고 개선안을 도출하는 능력' },
                scoringType: '5grade',
                scoring: cloneScoring(scoring10),
            },
            {
                id: 604,
                type: '정성',
                title: '협업 및 커뮤니케이션',
                weight: 0,
                details: { description: '팀 내외 소통과 협업 과정에서의 기여도' },
                scoringType: '5grade',
                scoring: cloneScoring(scoring10),
            },
            {
                id: 605,
                type: '정성',
                title: '자기 개발 및 학습',
                weight: 0,
                details: { description: '역량 향상을 위한 학습 및 적용 노력' },
                scoringType: '5grade',
                scoring: cloneScoring(scoring10),
            },
            {
                id: 606,
                type: '정성',
                title: '책임감 및 주도성',
                weight: 0,
                details: { description: '업무 주도성과 책임감, 일정 준수' },
                scoringType: '5grade',
                scoring: cloneScoring(scoring10),
            },
            {
                id: 607,
                type: '정성',
                title: '내부 고객 대응',
                weight: 0,
                details: { description: '요청 대응 속도/친절도/문제 해결 만족도' },
                scoringType: '5grade',
                scoring: cloneScoring(scoring10),
            },
            {
                id: 608,
                type: '정량',
                title: '핵심 KPI 달성률',
                weight: 0,
                details: { metric: 'KPI', target: '월별 목표', calculation: '실적/목표' },
                scoringType: '5grade',
                scoring: cloneScoring(scoring20),
            },
            {
                id: 609,
                type: '정량',
                title: '신규/업셀 실적',
                weight: 0,
                details: { metric: '매출', target: '월별 실적 목표', calculation: '실적 합산' },
                scoringType: '5grade',
                scoring: cloneScoring(scoring5),
            },
            {
                id: 610,
                type: '정량',
                title: '개선/자동화 제안',
                weight: 0,
                details: { metric: '개선 제안', target: '월별 개선 활동', calculation: '제안 건수/효과' },
                scoringType: '5grade',
                scoring: cloneScoring(scoring5),
            },
        ],
    },
    {
        id: 2,
        name: '프로젝트 동료 피드백',
        type: '다면 평가',
        category: '개발',
        tags: ['프로젝트', '협업'],
        version: 1,
        questions: 8,
        lastUpdated: '2024-06-15',
        author: '정현옥',
    },
    {
        id: 3,
        name: '신규 입사자 수습 평가',
        type: '수습 평가',
        category: '공통',
        tags: ['온보딩'],
        version: 1,
        questions: 15,
        lastUpdated: '2024-04-20',
        author: '장주휘',
    },
    {
        id: 4,
        name: '리더십 역량 진단',
        type: '리더십 평가',
        category: '리더십',
        tags: ['리더십'],
        version: 1,
        questions: 20,
        lastUpdated: '2024-03-01',
        author: '시스템',
    },
    {
        id: 5,
        name: 'Sales 직군 역량 평가',
        type: '역량 평가',
        category: '영업',
        tags: ['영업'],
        version: 1,
        questions: 10,
        lastUpdated: '2024-07-01',
        author: '장주휘',
    },
];
